### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [rvilalta/ietf-te-path-computation#101]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：https://github.com/rvilalta/ietf-te-path-computation/blob/bb5023c4f6e8b4630aba22039f76a33a9fa528d3/draft-ietf-teas-yang-path-computation.xml

**Comment by italobusi** [comment]
@syclh : please check and let us know whether the changes in PR #102 resolves your concerns
