### ISSUE TITLE
Bulk of path computations

### ISSUE THREAD

**Issue by italobusi** [rvilalta/ietf-te-path-computation#14]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016 

Q.01:       Is rpc defined for a single computation? (no need of synchronization vector)

Context.01: PC-API

R.01:       no bulk of path compuations to reduce overhead and latency. 
Ideally provide the possibility to make a single request with a list of ingress nodes and a list of egress nodes (which leads to the computation of all the permutations).

**Comment by efralaz** [comment]
Bulk path computation is needed for the following applications:
1. Compute 2 or more paths in diversity : it's well known that computing one path first and then trying to find another path in diversity doesn't guarantee to find a diverse path (if it exists).
2. Compute 2 or more paths guaranteeing separate network resources to each one : being stateless, the RPC just compute a path and forget it. If no path deployment happens, repeating the path computation with the same parameters will return the same identical path. We want instead to know if it's possible to route a set of paths in the network, and know all their routes.
3. Optimize a set of paths (of course this needs to take into account all the paths at once). In PCEP the same primitive is used to do optimization and path computation; maybe here we can provide different primitives, but in any case some bulk capability is needed, here if path computation is going to be used also for optimization, as in PCEP.

**Comment by italobusi** [comment]
Call on 13 April 2017

These cases are described in RFC 5440

**Comment by italobusi** [comment]
I think that this issue has been closed with the addition of the synchronization list.

@efralaz : could you please check?
