### ISSUE TITLE
Source & Destination are references in network-topology

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#15]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q: source & destination are references in network-topology to termination point
Cons: not possible to request a computation between IP/Interfaces addresses not represented as TP 

Context: TE tunnel

R: check if the TE tunnel draft uses IP address or TP and if not align between TE tunnel, TE topo and PC-API.

**Comment by italobusi** [comment]
Italo/Sergio/Ricard:

It seems TE Tunnel can support tunnel setup between IP/interfaces addresses as well as TTPs:

`             +--rw source?                  inet:ip-ad
|  |  |  +--rw destination?             inet:ip-address
        |  +--rw src-tp-id?               binary
        |   +--rw dst-tp-id?               binary

leaf source {
         type inet:ip-address;
         description
           "TE tunnel source address.";
       }
  leaf destination {
         /* Add when check */
         type inet:ip-address;
         description
           "P2P tunnel destination address";
       }
    leaf src-tp-id {
         type binary;
         description
           "TE tunnel source termination point identifier.";
       }
     leaf dst-tp-id {
         /* Add when check */
         type binary;
         description
           "TE tunnel destination termination point identifier.";
`

@rvilalta : please align the Path Computation module with the TE Tunnel module

**Comment by rvilalta** [comment]
I don't understand. Path-computation also supports both:
    leaf source {
      type inet:ip-address;
      description
        "TE tunnel source address.";
    }
    leaf destination {
      /* Add when check */
      type inet:ip-address;
      description
        "P2P tunnel destination address";
    }
    leaf src-tp-id {
      type binary;
      description
        "TE tunnel source termination point identifier.";
    } 
    leaf dst-tp-id {
      /* Add when check */
      type binary;
      description
        "TE tunnel destination termination point identifier.";
    }

@carloperocchio Could you please describe the improvement to be made?
Thanks.

**Comment by carloperocchio** [comment]
In my opinion how to use these fields is unclear/unspecified (already in te-tunnel): are tp-id and ip-address alternative or complementary? 
For example in case of loopback interfaces used only to instantiate tunnels: must they be represented as termination-points in topology?
- 
Just a note: tp-id in the topology has to be unique only in the node: (I think) a tp-ref could be more appropriate but it should be clarified in the context of te-tunnel too.

**Comment by italobusi** [comment]
@rvilalta 

In the YANG model we have published in the -01 version of our I-D we have the following code:

>      grouping PathCompServicePort {
>        container src-tp-ref {
>          uses nt:tp-ref;
>          config false;
>          description "Source termination point reference.";
>        }
>        container dst-tp-ref {
>          uses nt:tp-ref;
>          config false;
>          description "Destination termination point reference.";
>        }
> 

In the current YANG model in GitHub, we have instead the following code:

>   grouping PathCompServicePort {
>     leaf source {
>       type inet:ip-address;
>       description "TE tunnel source address.";
>     }
>     leaf destination {
>       type inet:ip-address;
>       description "P2P tunnel destination address";
>     }
>     leaf src-tp-id {
>       type binary;
>       description "TE tunnel source termination point identifier.";
>     }
>     leaf dst-tp-id {
>       type binary;
>       description "TE tunnel destination termination point identifier.";
>     }
>     uses te-types:bidir-assoc-properties;
>     description "Path Computation Service Port grouping.";
>   }

I do not recall when we have made this change on GitHub, but I think this change has aligned our model with the TE Tunnel model.

**Comment by italobusi** [comment]
@carloperocchio : I think that the clarification and syntax issue (i.e., whether to use a tp-ref instead of a binary for identifying  a ttp) should be discussed with the TE Tunnel people

**Comment by italobusi** [comment]
Moreover, the new model is copying rather than using from the TE Tunnel model, which may be an issue if any change is done in the TE Tunnel model.

I think there is a general issue, also identified in the discussion of Issue #23, about whether path-computation RPC should use all parameters included in tunnel-params_config or only a subset.

**Comment by italobusi** [comment]
@rvilalta and @carloperocchio 

Based on the previous discussion items I think that:
- the bug has been fixed
- we need to discuss how to use the tunnel-params_config in our YANG model
- we need to request input from the TE Tunnel model about the use and syntax of these attributes

Therefore we can remove the "bug" label and add the "need discussion" and "support from TE tunnel needed" labels.

Do you agree?

**Comment by italobusi** [comment]
This issue is pending resolution of issue #23

**Comment by italobusi** [comment]
@carloperocchio : is this issue still open?
