### ISSUE TITLE
Unidirectional/Bidirectional

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#17]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q: Moreover is not included the possibility to specify unidir or bidir.

Context: TE-tunnel issue (also co-routed missing)

**Comment by italobusi** [comment]
Italo/Sergio/Ricard:

It seems that TE Tunnel support unidir and bidir. We need to align with TE module.

@rvilalta : Add

`uses te-types:bidir-assoc-properties`
