### ISSUE TITLE
Relaxable and non-relaxable constraints

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#19]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q: A constraint can be present but it’s not possible to specify it is optional.
When a constraint is present, has to be intended mandatory?

Context: PC-API and TE Tunnel

R: in PCEP it is possible to specify if a constraint is mandatory, optional, if the path computation must fail if the constraint is not met or to relax the constraint. It should be possible to have the same behavior.

**Comment by ietf-mpls-yang** [comment]
We will discuss this in the next TE YANG model

**Comment by italobusi** [comment]
Title changed to reflect resolution of the comments from IETF 98

**Comment by sergiobelotti** [comment]
Could we close the issue in the list since we understand the reference now for the indicated problem i.e. relaxable and not-relaxable constraints is the issue #35 ?

**Comment by sergiobelotti** [comment]
The issue is closed and the related subject is covered in issue #35
