### ISSUE TITLE
Tiebreaker associated behavior

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#22]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q: Which are the requested behaviors associated to tiebreaker possible values (min fill, max fill)?

Context: PC-API

R: to verify the meaning of min fill and max fill and understand if other values should be included

**Comment by italobusi** [comment]
We need help from the TE Tunnel experts

@carloperocchio : please change the label to "support from TE Tunnel needed"

**Comment by sergiobelotti** [comment]
I think that we can consider this issue as closed after metric and optimization discussion and yang modification. Tiebreaker is used as further "metric" in case optimization based of the previous list of metrics, gives as result ECMP.
rw optimization-metrics
       |  |     |  +--rw optimization-metric* [metric-type]
       |  |     |     +--rw metric-type    -> ../config/metric-type
       |  |     |     +--rw config
       |  |     |     |  +--rw metric-type?   identityref
       |  |     |     |  +--rw goal?          te-types:optimization-goal
       |  |     |     |  +--rw weight?        uint8
       |  |     |     +--ro state
       |  |     |        +--ro metric-type?   identityref
       |  |     |        +--ro goal?          te-types:optimization-goal
       |  |     |        +--ro weight?        uint8
       |  |     +--rw objective-functions
       |  |     |  +--rw objective-function* [objective-function-type]
       |  |     |     +--rw objective-function-type    -> ../config/objective-function-type
       |  |     |     +--rw config
       |  |     |     |  +--rw objective-function-type?   identityref
       |  |     |     |  +--rw weight?                    uint8
       |  |     |     +--ro state
       |  |     |        +--ro objective-function-type?   identityref
       |  |     |        +--ro weight?                    uint8
       |  |     +--rw tiebreakers
       |  |     |  +--rw tiebreaker* [tiebreaker-type]
       |  |     |     +--rw tiebreaker-type    -> ../config/tiebreaker-type
       |  |     |     +--rw config
       |  |     |     |  +--rw tiebreaker-type?   identityref
       |  |     |     +--ro state
       |  |     |        +--ro tiebreaker-type?   identityref

**Comment by carloperocchio** [comment]
rpc to be updated

**Comment by sergiobelotti** [comment]
Not clear what update should be done in rpc .

**Comment by italobusi** [comment]
Maybe we just need to recompile the YANG module with the latest TE YANG modules and check that the resulting RPC is fine

**Comment by sergiobelotti** [comment]
@rvilalta need to re-compile path computation module with the new te-types

**Comment by italobusi** [comment]
Proposed resolution proposed in pull request #41
