### ISSUE TITLE
Missing class type

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#25]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q: Class type for diff serv is missing.

Context: TE tunnel 

R:  clarify if this goes into technology specific extensions (for MPLS) or should go in the generic part.

**Comment by ietf-mpls-yang** [comment]
For TE interfaces, we have:
augment /te:te/te-dev:interfaces/te-dev:interface:
   +--rw config
   |  +--rw (bandwidth-value)?
   |  |  +--:(absolute)
   |  |  |  +--rw absolute-value?   uint32
   |  |  +--:(precentage)
   |  |     +--rw percent-value?    uint32
   |  +--rw (bc-model-type)?
   |     +--:(bc-model-rdm)
   |     |  +--rw bc-model-rdm
   |     |     +--rw bandwidth-mpls-constraints
   |     |        +--rw maximum-reservable?   uint32
   |     |        +--rw bc-value*             uint32
   |     +--:(bc-model-mam)
   |     |  +--rw bc-model-mam
   |     |     +--rw bandwidth-mpls-constraints
   |     |        +--rw maximum-reservable?   uint32
   |     |        +--rw bc-value*             uint32
   |     +--:(bc-model-mar)
   |        +--rw bc-model-mar
   |           +--rw bandwidth-mpls-constraints
   |              +--rw maximum-reservable?   uint32
   |              +--rw bc-value*             uint32

**Comment by ietf-mpls-yang** [comment]
For LSP, we may be missing the bandwidth class-type when computing path for the lsp. Taking AI to Look into it

**Comment by italobusi** [comment]
In the -06 version we have:

```
       |  |     |     |  +--rw class-type?
                                te-types:te-ds-class

```

@carloperocchio : can we close this open issue?

**Comment by carloperocchio** [comment]
As agreed with Italo, reopened to wait for path computation rpc definition update

**Comment by italobusi** [comment]
@rvilalta : could we update the YANG path computation RPC using the latest version of the te-tunnel model (in the -06 draft) and check that the class-type gets added?

Thanks, Italo

**Comment by sergiobelotti** [comment]
In TE-tunnel (as in teas-topo) it has been made effort to avoid technology specific parameter: I was wondering if this parameter is correct to report in the technology agnostic part.

**Comment by italobusi** [comment]
In draft-ietf-teas-yang-te-08 the class-type is now defined withint the ietf-te-mpls@2017-06-29.yang module

For path computation, it may need to be defined in some MPLS-TE augmentation of the path computation RPC.

@carloperocchio : can we consider this issue closed?

**Comment by carloperocchio** [comment]
the yang data module ietf-te-mpls.yang is included in teas-yang-te draft with ietf-te.yang.
Do you plan to put together in the same document?

**Comment by ietf-mpls-yang** [comment]
It is an augmentation to constraints from the packet model.. Do you think this is applicable to non-packet too?
![image](https://user-images.githubusercontent.com/9702603/42661888-9de10450-85fd-11e8-8835-cc1e8d9689c1.png)

**Comment by italobusi** [comment]
Open issue https://github.com/ietf-mpls-yang/te/issues/37 closed

This attribute should be defined in the MPLS augmentations for TE Tunnel and Path Computation
