### ISSUE TITLE
adding _includeTopology and _excludeTopology path constraints 

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#27]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q:       Which is the usage foreseen for topology-id in path constraints?

R:       It is used to include or exclude a give topology. Just one at time.

**Comment by italobusi** [comment]
@rvilalta : can we start updating the YANG model making the _avoidTopology a list and adding the _includeTopology?

**Comment by italobusi** [comment]
@carloperocchio : I think this issue should be labelled as "need discussion"

**Comment by GianmarcoBruno** [comment]
What about renaming _avoidTopology to _excludeTopology as it is more consistent to those familiar with PCEP?

**Comment by italobusi** [comment]
This is the definition of the topology-id in the ietf-te-types.yang module:

```
      leaf topology-id {
        type te-types:te-topology-id;
        description
          "The tunnel path is computed using the specific
          topology identified by this identifier";
      }

```

**Comment by ietf-mpls-yang** [comment]
topology-id is used as an additional constraint to force the path to be computed in a specific topology

**Comment by italobusi** [comment]
**Call April 13 2017**

It seems that the use of the topology-id attribute in TE Tunnel model is not fully clear.
Need support from TE Tunnel model authors.

**Comment by italobusi** [comment]
The topology-id attribute gives context to the references to the topological entities (e.g., node-id, ttp-id, ltp-id) used within the TE Tunnel

**Comment by italobusi** [comment]
Still needs to discuss whether we need to constraint path computation with _includeTopology and _excludeTopology path constraints

**Comment by italobusi** [comment]
Pending clarification of the underlying requirement in ONF

It can be added in a future update (even a future RFC) after the requirements is clarified

**Comment by italobusi** [comment]
Outside the scope of the current document

We may consider this enhancement for a future RFC once the ONF requirement is clarified
