### ISSUE TITLE
Capacity units

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#28]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q:       Is requested capacity in byte/sec? 
            What about other technologies like WDM or OTN? 
            How coordinate it with te-bandwidth in te-topology?

R:       Under discussion (import from RSVP model).

**Comment by ietf-mpls-yang** [comment]
for MPLS/packet, it is defined in ietf-rsvp-te-mpls.yang.
for other technologies need to define in respective module for otn/wdm

**Comment by sergiobelotti** [comment]
In te-types there is the generic way to express bw:
typedef te-bandwidth {
    type string {
      pattern
        '0[xX](0((\.0?)?[pP](\+)?0?|(\.0?))|'
      + '1(\.([\da-fA-F]{0,5}[02468aAcCeE]?)?)?[pP](\+)?(12[0-7]|'
      + '1[01]\d|0?\d?\d)?)|0[xX][\da-fA-F]{1,8}|\d+'
      + '(,(0[xX](0((\.0?)?[pP](\+)?0?|(\.0?))|'
      + '1(\.([\da-fA-F]{0,5}[02468aAcCeE]?)?)?[pP](\+)?(12[0-7]|'
      + '1[01]\d|0?\d?\d)?)|0[xX][\da-fA-F]{1,8}|\d+))*';
    }
    description
      "This is the generic bandwidth type that is a string containing
       a list of numbers separated by commas, with each of these
       number can be non-negative decimal, hex integer, or hex float:
       (dec | hex | float)[*(','(dec | hex | float))]
       For packet switching type, a float number is used, such as
       0x1p10.
       For OTN switching type, a list of integers can be used, such
       as '0,2,3,1', indicating 2 odu0's and 1 odu3.
       For DWDM, a list of pairs of slot number and width can be
       used, such as '0, 2, 3, 3', indicating a frequency slot 0 with
       slot width 2 and a frequency slot 3 with slot width 3.";
  } // te-bandwidth

There has been concerns (e.g. for OTN) highlighted by Francesco . 
Shall we consider this as closed with this generic definition? (used also in teas -topo)

**Comment by italobusi** [comment]
It would be simpler if we can propose an alternative solution with a generic container which  can be augmented with technology-specific bandwidth information

Let's keep the issue open and prepare an alternative solution for discussion with TE Topology and TE Tunnel authors

**Comment by italobusi** [comment]
I think that this issue has been closed with the definition of the te-bandwidth grouping  in te-types which is used by the Path Computation RPC

@carloperocchio : please check
