### ISSUE TITLE
Missing IRO and XRO 

### ISSUE THREAD

**Issue by carloperocchio** [rvilalta/ietf-te-path-computation#29]
Questions and answers discussion: Italo Busi, Sergio Belotti, Daniele Ceccarelli, Francesco Lazzeri, Gianmarco Bruno, Carlo Perocchio
Monday, December 05, 2016

Q:       Include and exclude route object are not available (incomplete definitions for _includePath and _excludePath are commented out)

R:       They can be done per ERO or using the affinities (comment from Tarek). To be checked.

**Comment by ietf-mpls-yang** [comment]
please look into:

  identity route-usage-type {
    description
      "Base identity for route usage";
  }

  identity route-include-ero {
    base route-usage-type;
    description
      "Include ERO from route";
  }

  identity route-exclude-ero {
    base route-usage-type;
    description
      "Exclude ERO from route";
  }

and 

        leaf explicit-route-usage {
          type identityref {
            base te-types:route-usage-type;
          }
          description "An explicit-route hop action."
        }

**Comment by ietf-mpls-yang** [comment]
AI: TE tunnel model to look into it
list1 (EROs) -> exclude
list2 (EROs) -> include
note: include + exclude for same ERO -> unexpected.

**Comment by italobusi** [comment]
@ietf-mpls-yang : I think it is also useful to clarify that:
- exclude list is not ordered (or order does not matter)
- include list is ordered

**Comment by efralaz** [comment]
I believe that the "note: include + exclude for same ERO -> unexpected", means that the two lists must not include the same resources. Both of them can well be present inside the same request, though: one can request a path through a certain set of points AND avoid a different set of resources at once.

**Comment by sergiobelotti** [comment]
In case a resource (node or link) would be present in both Include and Exclude list , a syntax check can be done. However it does not cover all possible combinations of exclude , include list that would lead path computation to find no path. In other words the consistency check is performed by path computation itself.

**Comment by italobusi** [comment]
**TE Tunnel call (April 21)**

Keep the existing list as it is (representing the IRO) and add a new exclude-always-list (representing the XRO).
The exclude-always-list is not ordered.

**Comment by sergiobelotti** [comment]
In tte-tunnel a new list list route-object-include-exclude has been added .
There is an exclude-only list and the above one.

grouping path-route-objects {
    description
      "List of EROs to be included or excluded when performing
       the path computation.";
    container explicit-route-objects {
      description
        "Container for the exclude route object list";
      list route-object-exclude-always {
        key index;
        description
          "List of explicit route objects to always exclude
           from path computation";
        leaf index {
          type leafref {
            path "../config/index";
          }
          description
            "Index of this explicit route object";
        }
        uses te-types:explicit-route-hop;
      }
      list route-object-include-exclude {
        key index;
        description
          "List of explicit route objects to include or
           exclude in path computation";
        leaf index {
          type leafref {
            path "../config/index";
          }
          description
            "Index of this explicit route object";
        }
        leaf explicit-route-usage {
          type identityref {
            base te-types:route-usage-type;
          }
          description "Explicit-route usage.";
        }
        uses te-types:explicit-route-hop;
      }
    }
  }

Shall we consider this as closed?

**Comment by italobusi** [comment]
I think there is some overlapping/duplication now between the named-explicit-paths and the route-object-include-exclude list within named-path-constraints. However, I think this is another issue.
This issue is closed IMHO.

**Comment by carloperocchio** [comment]
rpc to be updated

**Comment by italobusi** [comment]
@rvilalta : I think we need to update the RPC to use the path-route-objects from te-types

**Comment by efralaz** [comment]
Looking at path-route-objects and the relevant explicit-route-hop_config, it seems that there is no way to specify SRLGs, which are an option for exclusion: it's sensible and valuable feature in my view to have the possibility to request a path avoiding a given SRLG.

**Comment by italobusi** [comment]
Proposed resolution available in pull request #41
