### ISSUE TITLE
Benoit's issue (2018-01-08)

### ISSUE THREAD

**Issue by sergiobelotti** [rvilalta/ietf-te-path-computation#36]
Hi,
You're missing a revision in

   
  ` <CODE BEGINS>file " ietf-te-path-computation.yang "`

See https://datatracker.ietf.org/doc/draft-ietf-netmod-rfc6087bis/

Regards, Benoit

**Comment by sergiobelotti** [comment]
To solve the issue we just need to update internet draft with :
``<CODE BEGINS>file " ietf-te-path-computation@2017-11-13.yang "
Obviously we need to put the correct date of new uploading.

**Comment by italobusi** [comment]
The -01 has just been submitted for IETF 101
