### ISSUE TITLE
Align with path-access-segment-info grouping of te-tunnel

### ISSUE THREAD

**Issue by sergiobelotti** [rvilalta/ietf-te-path-computation#46]
In te-àtunnel a grouping has been added to provide access-label in case of multi-domain path calculation. 
The client has to provide a label set to access and exit a domain , to make able the domain controller to calculate path considering the provided label related to the previous and followed domain (in case e.g. of 3 domains scenario) .
grouping path-access-segment-info {
    description
      "If an end-to-end tunnel crosses multiple domains using
       the same technology, some additional constraints have to be
       taken in consideration in each domain";
    container path-in-segment {
      presence
        "The end-to-end tunnel starts in a previous domain;
         this tunnel is a segment in the current domain.";
      description
        "This tunnel is a segment that needs to be coordinated
         with previous segment stitched on head-end side.";
      uses access-segment-info;
    }
    container path-out-segment {
      presence
        "The end-to-end tunnel is not terminated in this domain;
         this tunnel is a segment in the current domain.";
      description
        "This tunnel is a segment that needs to be coordinated
         with previous segment stitched on head-end side.";
      uses access-segment-info;
    }
  }

**Comment by italobusi** [comment]
Italo/Sergio: the issue is solved with commit 2054a0e
