### ISSUE TITLE
path computation in a flat/distributed approach

### ISSUE THREAD

**Issue by sergiobelotti** [rvilalta/ietf-te-path-computation#61]
It was raised question in the mailing list  if path computation solution presented in this draft takes into account also  distributed path computation as per RFC5441 (Backward-Recursive PCE-Based Computation (BRPC) Procedure ). The issues is when in a multi-domain scenarios, networks/domains are own by different operators, or business unit within the same operator. In this case  it is not always feasible to add a  parent/orchestrator centralized controller managing all multi-operators networks . In this case, TE information must be exchanged directly between lower controller e.g. between TE Domain Controller, DC Controller and TE Network Controller, Packet and Optical Network Controller.
So the typical "hierarchical" scenarios we have used as architectural assumption in the draft can be turned into a "flat/distributed" scenarios in which there are peer to peer controller exchanging information.
reference https://mailarchive.ietf.org/arch/msg/teas/k0QQkOQTzjPWlWinwjtBCfz0wMo

**Comment by sergiobelotti** [comment]
One possibility to address this scenario without changing hierarchical approach is explained here 
https://mailarchive.ietf.org/arch/msg/teas/G8aUC9FFfPUkt9Q7FL-8C7eVeoQ
Attached related slides 
[slide-101218-Oliver.pptx](https://github.com/rvilalta/ietf-te-path-computation/files/2837069/slide-101218-Oliver.pptx)

Comment on this proposal can be found in 
https://mailarchive.ietf.org/arch/msg/teas/-abohI_WDkKdc6JoyeK04wM2b4Q

**Comment by italobusi** [comment]
Based on IETF 104 discussion:
- need to understand which modifications are needed to the current YANG model
- add text describing the applicability of the RPC to the distributed scenario

**Comment by sergiobelotti** [comment]
2019-06-06
Call among Italo, Sergio, Julien and Olivier:
We agree that the Yang model in the current draft can support both hierarchical and flat-distributed approaches.

The big difference is that the request coming at the NBI of domain controller A request an end to end path where the destination can be outside of the network domain controlled by the domain controller A.
It is the job of domain controller A to understand that the destination point is not within his domain and use PCEP/BRCP procedure toward peer domain controller(s) to compute the multi-domain path.
or Hierachical PCEP communication as per RFC 6805 and draft-ietf-pce-statefull-hpce-08.txt. 

Attached updated slides.
[distributed-flat-path-computation v01.pptx](https://github.com/rvilalta/ietf-te-path-computation/files/3325384/distributed-flat-path-computation.v01.pptx)

Actions:
1) Italo/Sergio : to explicitly say in the draft the described use cases  are just not exhaustive examples and do not preclude using the Yang model in other use cases (e.g., using a flat-distributed approach). 
2) Julien/Olivier : Add use cases for BRPC and H-PCE where a Yang based protocol, such as Restconf or Netconf, is used to request a path to the first domain controller respectively the Parent PCE.

**Comment by italobusi** [comment]
Close with the latest draft updated: https://tools.ietf.org/html/draft-ietf-teas-yang-path-computation-06
