### ISSUE TITLE
return path properties in case of no-path

### ISSUE THREAD

**Issue by sergiobelotti** [rvilalta/ietf-te-path-computation#63]
There are use cases (e.g., optical parameters) where path properties deserve to be returned to the requester in case of no-path, so that it can be aware of the blocking item and adapt furthers requests; a possible way to address that could be to:
  * include a branch "path-properties" under the "no-path" to convey some optional properties,
  * add a "blocking reason" under "no-path", in the spirit of the PCEP's NO-PATH-VECTOR (https://www.iana.org/assignments/pcep/pcep.xhtml#no-path-vector-tlv);

**Comment by italobusi** [comment]
@ju7ien : please review the current proposal and on-going discussion on TE github: https://github.com/tsaad-dev/te/issues/54#issuecomment-567459715

**Comment by italobusi** [comment]
@italobusi , @sergiobelotti : update the YANG model in alignment with the resolution of https://github.com/tsaad-dev/te/issues/54
