### ISSUE TITLE
metric accumulative attribute type

### ISSUE THREAD

**Issue by sergiobelotti** [rvilalta/ietf-te-path-computation#64]
metric's accumulative-value is currently defined as a "uint64 whereas it doesn't fit optical metrics at all, a decimal variation would be far more appropriate;

**Status**
- [x] Pending resolution of https://github.com/tsaad-dev/te/issues/55
- [ ] To be closed

**Comment by italobusi** [comment]
Discussed and agreed with TE tunnel team: https://github.com/tsaad-dev/te/issues/55#issuecomment-565501827

> Agreement:
> 
> * new augmentation (via new optical module) for optical path attributes
> * new list for metric types that do not fit in uint64 bits
> * may do leaf_type leaf_value for different attributes types

**Comment by italobusi** [comment]
This issue should be addressed in the optical models augmentations of TE Tunnel and Path Computation
