### ISSUE TITLE
bidirectional path with asymmetric path properties

### ISSUE THREAD

**Issue by sergiobelotti** [rvilalta/ietf-te-path-computation#65]
The module misses a mechanism to include a metric's accumulative-value per direction, e.g. we could have a bidirectional WDM LSP with 2 different SNR values, one for the downstream direction and one for the upstream direction.

A possible solution could be to add an optional "upstream" branch carrying relevant properties.

- [ ] @sergiobelotti : send a mail to the TEAS WG mailing list to report the output of this discussion

**Comment by italobusi** [comment]
I think we should consider the following cases:

`               - symmetric constraints ----- symmetric properties
             /                         \
            /                           \
bidir path -                             \
            \                             \
             \- asymmetric constraints ----- asymmetric properties `

**Comment by italobusi** [comment]
**2021-04-30 TEAS call**

When asymmetric path properties with symmetric constraints are allowed, the reverse path is configured with empty explicit-route-object (to indicate that the reverse path is co-routed with the forward path) and no path constraints (to indicate that the path constraints are the same as the forward path).

When asymmetric path properties with symmetric constraints are not allowed, the reverse path is not configured.

It is also possible to request the setup of co-routed paths with asymmetric constraints: the reverse path is configured with empty explicit-route-object (to indicate that the reverse path is co-routed with the forward path) and with the path constraints which are different from those defined for the forward path.

@sergiobelotti @italobusi : update the RPC model to align with this behavior

**Comment by italobusi** [comment]
**2021-05-13 Italo/Sergio**

The current RPC model already supports reporting bidirectional path with asymmetric path properties as described in https://github.com/rvilalta/ietf-te-path-computation/issues/65#issuecomment-830171068:
- two path request should be defined (one for the forwarding and one for the reverse direction)
- the path request for the reverse path should have an empty route-object-include-exclude and no path constraints
- the path response will report the path properties for the forward and reverse paths

**Comment by italobusi** [comment]
@sergiobelotti : send a mail to the TEAS WG mailing list to report the output of this discussion

**Comment by sergiobelotti** [comment]
> @sergiobelotti : send a mail to the TEAS WG mailing list to report the output of this discussion
Done .
