### ISSUE TITLE
Some Editorial considertions on the draft

### ISSUE THREAD

**Issue by haomianzheng** [rvilalta/ietf-te-path-computation#68]
1.	The concept of path computation data model and the PCE should be orthogonal, i.e., we should avoid misleading that the path computation data model must be achieved via PCEP, especially among controllers; please help clarify if this understanding is correct; 
2.	Section 3.3 mentions the ‘stateless’ and ‘stateful’ path computation respectively, but the term is slightly confusing because it reminds people to use stateful/stateless PCEP to do the path computation work, which is actually just a sub-case in the path computation model. I think the motivation to have ‘stateful/stateless’ here is ‘to plan the network with or without actually occupying any resources’, so probably some alternative terminologies can be used. I don’t have perfect term in my mind, but something like ‘compute-reserve’ and ‘compute-only’ may be helpful; 
3.	Section 3.2 provides really detailed path computation policies, I know we have hard experience to achieve here. The content is clear but seems an overkill. Shall we leave some path computation principles here, and move the details as an example to some appendix? 

We are also trying to re-trigger some discussion on the list to drive this document to maturity & publication. Let's use the list to follow up how to move:)

Haomian & Yanlei

**Comment by italobusi** [comment]
**2020-03-12 Italo/Sergio**

We have addressed your comments 1 and 2 in this updated editors'draft: 
[draft-ietf-teas-yang-path-computation-09@2020-03-12.docx](https://github.com/rvilalta/ietf-te-path-computation/files/4325164/draft-ietf-teas-yang-path-computation-09%402020-03-12.docx)

Regarding comment 1, we have added some clarification statement in section 1:

> The YANG model definition does not make any assumption about whether that the client or the server implement a “PCE” functionality, as defined in [RFC4655], and the PCEP protocol, as defined in [RFC5440].

Regarding comment 2, we are removed the terms stateful/state-less where not necessary to describe the behavior of the solution

We will review section 3.2 in the next days

@haomianzheng : please review the proposed changes

**Comment by haomianzheng** [comment]
> **2020-03-12 Italo/Sergio**
> 
> 
> @haomianzheng : please review the proposed changes

I am okay with the resolution of comment 1 & 2.

**Comment by italobusi** [comment]
**2020-05-25 Italo/Sergio**

It seems not easy to move the content of section 3.2 in an Appendix

We have tried to summarize the main concepts in section 3.2 pointing to sub-sections 3.2.x for details

See updated editors' draft: https://github.com/rvilalta/ietf-te-path-computation/pull/70#issuecomment-633646734

@haomianzheng : please review the proposed changes to section 3.2

**Comment by haomianzheng** [comment]
The proposed changes in section 3.2 in #70 is good to close this issue.
