### ISSUE TITLE
Section 5 Text: about the association among RPC, Request and Path reply

### ISSUE THREAD

**Issue by haomianzheng** [rvilalta/ietf-te-path-computation#72]
What we have understood from the current text in Section 5 about RPC is: 
1 RPC can include multiple requests, let's say N; 
For each request, there can be multiple paths computed, let's say M; 
Then 1 RPC can be replied with NxM paths, and the question is, how many request-id do we have? Is it N or NxM? 

Text change proposal: 
OLD: 
`This YANG model allows one RPC to include multiple path requests, each path request being identified by a request-id. Therefore, one RPC can return multiple responses, one for each path request, being identified by a response-id equal to the corresponding request-id.`
NEW: (if N)
`This YANG model allows one RPC to include multiple path requests, each path request being identified by a request-id. Meanwhile, one request, being identified by a response-id equal to the corresponding request-id, can only return one response with one or multiple paths computed.`
NEW2: (if NxM)
`This YANG model allows one RPC to include multiple path requests, each request being identified by a request-id. One request can return one response with multiple paths computed, each paths with a respective response-id. Multiple response-ids can be associated with one corresponding request-id. `

**Comment by italobusi** [comment]
**2020-05-25 Italo/Sergio**

We have updated the text to clarify that there are N responses where each response can report M computed paths

**Comment by italobusi** [comment]
@haomianzheng : please review the proposed text changes

**Comment by haomianzheng** [comment]
The update in section 5 of #70 is fine to close this issue.
