### ISSUE TITLE
Hop cumulative path metric

### ISSUE THREAD

**Issue by italobusi** [rvilalta/ietf-te-path-computation#77]
What is a "Hop cumulative path metric"? The description should be enhanced. Is it defined elsewhere? If so, add reference.

_Originally posted by @dieterbeller in https://github.com/rvilalta/ietf-te-path-computation/pull/70_

**Comment by italobusi** [comment]
@efralaz : where the  "Hop cumulative path metric" has been defined?

In RFC5441, we can only find:

      Type 4: Aggregate bandwidth consumption.

      Type 5: Load of the most loaded link.

      Type 6: Cumulative IGP cost.

      Type 7: Cumulative TE cost.

**Comment by italobusi** [comment]
After some offline discussion with @efralaz , it has been clarified that this metric is not defined in RFC5441.

However, this seems to be the "cumulative" variant of the Hop path metric defined in RFC8776:

```
     identity path-metric-hop {
       base path-metric-type;
       description
         "Hop path metric.";
     }

```

@dieterbeller : what about redefining it as "Cumulative hop path metric" and referencing RFC8776?

```
  identity svec-metric-cumul-hop {
    base svec-metric-type;
    description
      "Cumulative hop path metric.";
    description
      "RFC8776: Common YANG Data Types for Traffic Engineering";
  }

```

Co-authored-by: sergiobelotti <sergio.belotti@nokia.com>

**Comment by dieterbeller** [comment]
The proposed reference to [RFC8776](https://tools.ietf.org/html/rfc8776) in in the description of `identity svec-metric-cumul-hop` (see: https://github.com/rvilalta/ietf-te-path-computation/issues/77#issuecomment-764747930 above) looks good to me.
