### ISSUE TITLE
Tom Petch's comments on 2021-03-30

### ISSUE THREAD

**Issue by italobusi** [rvilalta/ietf-te-path-computation#87]
See: https://mailarchive.ietf.org/arch/msg/teas/9gYSG97P4HkAaRBbPi1pyjnl3ew/

> Looks good (mostly:-).  I like the capitalisation.  Bringing my comments up to the top lest they get lost. Mostly editorial but
> 
> te-types has a type for tp-id; why not use it? or explain why it is not suitable

IBSB> The te-types:te-tp-id can be used to reference LTPs. In order to reference TTPs, the binary type is needed because RFC 8795, defines the TTP IDs as binary. YANG model has been updated to clarify that this is a tunnel-tp-id.

- [x] YANG model to be updated as in the latest version of ietf-te

> 
> 
> I still see one inconsistency of YYYY and XXXX both of which get used for teas-yang-te; I think YYYY better since XXXX is usually used for 'this' I-D.

IBSB> used YYYY in -13 version

> 
> Expansions needed for OSNR BER (which defaults to Basic Encoding Rules), FEC, WDM, e2e(probably)

IBSB>OK, done in -13 version

> 
> s.1
> /allows providing the TED/allows the provisioning of the TED/

IBSB>OK, done in -13 version

> 
> s.3.2
> /may be not sufficient/may be insufficient/

IBSB>OK, done in -13 version (also in the abstract and introduction)

> 
> s.3.2.1
> /by its own /on its own /

IBSB>OK, done in -13 version

> 
> s.3.3..3
> / it is know/ it is known/

IBSB>OK, done in -13 version

> 
> s.3.3
> /does not guaranteed /does not guarantee /

IBSB>OK, done in -13 version

> 
> s.6.2
> "RFC XXXX: Yang model for requesting Path Computation";
> 
> RFC XXXX: YANG Data Model for requesting Path Computation to match the title of the I-D
> 

IBSB>OK, done in -13 version

- [x] OK, YANG model to be updated

> /as described in section 3.3.1.";/
> as described in section 3.3.1 of RFC XXXX.";/
> 

- [x] OK, YANG model to be updated

IBSB>OK, done in -13 version

> /  "Information for synchonized path computation /  "Information for synchronized path computation /
> 

- [x] OK, YANG model to be updated

IBSB>OK, done in -13 version

>      augment "/te:tunnels-actions/te:output" {
>        description
>          "Augment Tunnels Action RPC input ...
> /input/output/?
> 

- [x] It should be output. YANG model to be updated

IBSB>It should be output: fixed in -13 version

> s.8 I think that the analysis by leaf is needed before Last Call.
> 

IBSB>Yes, we have planned to do before requesting WG LC once the YANG model is stable. See open issue:

https://github.com/rvilalta/ietf-te-path-computation/issues/75

> on k-shortest, no I have no better idea.  Probably just ignorance on my part.  See what the AD or IESG come up with - it is the sort of technical reference where they excel.

IBSB>Ok, let's see if we can get some suggestions from WG, AD or IESG

**Comment by sergiobelotti** [comment]
> Information for synchonized path computation

**Comment by italobusi** [comment]
- [ ] @italobusi , @sergiobelotti : send a mail reply to Tom after the -13 revision has been uploaded
