### ISSUE TITLE
Move groupings to ietf-te or ietf-te-types

### ISSUE THREAD

**Issue by italobusi** [rvilalta/ietf-te-path-computation#89]
The following two groupings have been defined by copying a sub-set of the attributes defined in ietf-te YANG model:

https://github.com/rvilalta/ietf-te-path-computation/blob/826da8036051a1eb25698f4ba735dc4c8b591b4a/ietf-te-path-computation.yang#L508-L562

It is worthwhile checking if these two groupings can be moved to either ietf-te or ietf-te-types and re-used by both ietf-te and ietf-te-path-computation YANG models

- [x] Pending resolution of https://github.com/tsaad-dev/te/issues/150

**Comment by sergiobelotti** [comment]
It could be a good idea to share these grouping putting in ietf-te-types even if an RFC 8776. If this would be a problem (since already  an RFC),
I would leave the groupings where they are: I do not see any advantage  to move them into ietf-te.
